[project]
name = "ye-eun Lee"
version = "0.0.1"
description ="Iris-classifier"
readme = "README.md"
require-python = ">3.8"
[[project.authors]]
email = "dldpdms3406@naver.com"
name = "ye-eun Lee"
